// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200703112157_LocationSingerSeeding")]
    partial class LocationSingerSeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Concert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Price")
                        .HasColumnType("bigint")
                        .HasMaxLength(6);

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Concerts");
                });

            modelBuilder.Entity("Entities.ConcertSinger", b =>
                {
                    b.Property<Guid>("SingerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConcertId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SingerId", "ConcertId");

                    b.HasIndex("ConcertId");

                    b.ToTable("ConcertSinger");
                });

            modelBuilder.Entity("Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("County")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bf6d2c0e-b636-4f51-94ff-aab3406427c8"),
                            Country = "Romania",
                            County = "Bucuresti",
                            Name = "Bucuresti",
                            Street = "Strada z"
                        },
                        new
                        {
                            Id = new Guid("bf6d2c1e-b636-4f51-94ff-aab3406427c8"),
                            Country = "Romania",
                            County = "Iasi",
                            Name = "Iasi",
                            Street = "Strada x"
                        },
                        new
                        {
                            Id = new Guid("bf6d2c2e-b636-4f51-94ff-aab3406427c8"),
                            Country = "Romania",
                            County = "Brasov",
                            Name = "Brasov",
                            Street = "Strada y"
                        });
                });

            modelBuilder.Entity("Entities.Singer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MusicType")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Singers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5880919e-ab87-4f3b-aac3-d12513a40103"),
                            MusicType = "Pop",
                            Name = "Rihanna"
                        },
                        new
                        {
                            Id = new Guid("4880919e-ab87-4f3b-aac3-d12513a40103"),
                            MusicType = "Rock",
                            Name = "The weekend"
                        },
                        new
                        {
                            Id = new Guid("3880919e-ab87-4f3b-aac3-d12513a40103"),
                            MusicType = "Jazz",
                            Name = "Delia"
                        });
                });

            modelBuilder.Entity("Entities.Concert", b =>
                {
                    b.HasOne("Entities.Location", "Location")
                        .WithMany("Concerts")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.ConcertSinger", b =>
                {
                    b.HasOne("Entities.Concert", "Concert")
                        .WithMany("Singers")
                        .HasForeignKey("ConcertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Singer", "Singer")
                        .WithMany("Concerts")
                        .HasForeignKey("SingerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
